// <auto-generated />
namespace AudioVolume.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Addcontact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addcontact));
        
        string IMigrationMetadata.Id
        {
            get { return "202502272029374_Add-contact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
