// <auto-generated />
namespace AudioVolume.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updatesomet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatesomet));
        
        string IMigrationMetadata.Id
        {
            get { return "202502270803187_update-some-t"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
